spring.application.name=taskflow-api

spring.h2.console.enabled=true
#spring.datasource.generate-unique-name=false
#spring.datasource.name=taskflow
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=fabian
spring.datasource.password=password

spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

application.security.jwt.secret-key=VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdTZWNyZXRQcm9kdWN0aW9uS2V5Rm9ySFM=
application.security.jwt.expiration=60000

google.client-id=543928147429-0rlh5prc6th77tq0eumndpcpr01lqmtv.apps.googleusercontent.com